# Generated by Django 5.2 on 2025-05-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0005_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOCRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('Internship', 'Internship'), ('Placement', 'Placement'), ('Higher Studies', 'Higher Studies'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('document', models.FileField(upload_to='noc_documents/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
